source: "./"
safe: true
lsi: false
pygments: true
markdown: rdiscount
# url: "http://theodinproject.github.io/curriculum" # FOR PRODUCTION
url: "http://localhost:4000" # FOR LOCAL TESTING use this one
